# Generated by Django 4.2.2 on 2023-07-14 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_book_date_published_book_published_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.PositiveIntegerField(help_text='Use the following format: YYYY', null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
