# Generated by Django 4.2.2 on 2023-07-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_options_alter_book_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.TextField(blank=True),
        ),
    ]
