# Generated by Django 4.2.2 on 2023-07-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_book_author_alter_book_bookshelf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.FileField(blank=True, max_length=500, upload_to='book_covers/'),
        ),
    ]
