# Generated by Django 4.2.2 on 2023-07-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookshelf',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='goodreads_book_id',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='loaned_to',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='location',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='series_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
